import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NFT Drop</title>
        {/* change meta tag */}
        <meta name="description" content="Generated by create next app" />
        {/* change logo */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world</h1>
    </div>
  );
}
